node {
    checkout scm
    stage('Backup Configuration as POL') {

       sh label: '', script: '''set -x 
       find . -name backup_fed.sh
       sudo -E su - axway ${WORKSPACE}/Backup_Config_Pol/backup_pol.sh
       sudo rm /tmp/na_na.log
       echo "/opt/axway/Axway-7.6.2/apigateway/posix/bin/managedomain --username=admin --password=changeme -g api-env -n api-env --download_archive --archive_output_dir=$HOME/backup_fed" >> backup_fed.sh
       bash -x backup_fed.sh
       '''
    }
    
    stage('Clone YAMLES Repo') {

       sh label: '', script: '''set -x 
       rm -rf YamlES
       git clone git@github.com:axwayhackathon/YamlES.git
       ls -l $WORKSPACE/YamlES
       '''
    }
    
    stage('Generate YAML to FED') {

       sh label: '', script: '''set -x 
       echo "Generate YAML to FED"
       '''
    }
    
    stage('Deploy FED to Gateway') {

       sh label: '', script: '''set -x 
       echo "Deploy FED to Gateway"
       FED_FILE=/var/lib/jenkins/backup_fed/37e94471-8540-428e-82d4-b60badc80e11.fed
       sudo rm /tmp/na_na.log
       #sudo -E su - axway /opt/axway/Axway-7.6.2/apigateway/posix/bin/managedomain --username=admin --password=changeme -g api-env --deploy --archive_filename=${FED_FILE}
       /opt/axway/Axway-7.6.2/apigateway/posix/bin/managedomain --username=admin --password=changeme -g api-env --deploy --archive_filename=${FED_FILE}
       '''
    }
}

