node {
    checkout scm
    stage('Backup Configuration as POL') {

       sh label: '', script: '''set -x 
       find . -name backup_fed.sh
       sudo -E su - axway ${WORKSPACE}/Backup_Config_Pol/backup_pol.sh
       '''
    }
    
    stage('Clone YAMLES Repo') {

       sh label: '', script: '''set -x 
       git clone git@github.com:axwayhackathon/YamlES.git
       ls -l $WORKSPACE
       '''
    
    stage('Generate YAML to FED') {

       sh label: '', script: '''set -x 
       git clone git@github.com:axwayhackathon/YamlES.git
       echo "Generate YAML to FED"
       '''
    }
    
    stage('Deploy FED to Gateway') {

       sh label: '', script: '''set -x 
       echo "Deploy FED to Gateway"
       '''
    }
}

